---
agent_list:
- 192.168.102.42
# Use this bootstrap_url value unless you have moved the DC/OS installer assets.
bootstrap_url: file:///opt/dcos_install_tmp
cluster_name: DCOS19
exhibitor_storage_backend: static
master_discovery: static
master_list:
- 192.168.102.41
public_agent_list:
- 10.116.104.99
resolvers:
- 192.168.102.10
ssh_port: 22
ssh_user: centos
use_proxy: 'true'
http_proxy: http://10.222.192.4:8080
https_proxy: http://10.222.192.4:8080  
no_proxy: 
- 'apps.10.116.104.99.xip.io'
- '127.0.0.1'
- 'localhost,'
- '169.254.169.254'
- '192.168.102.0/24'
